name: Only works for main

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

